const mongoose = require("mongoose");
const { secondaryDB } = require("../../config/secondaryDb");
const InternationalVisitorSchema = new mongoose.Schema(
  {
    eventName: { type: String },
    registrationId: { type: String, unique: true },
    registrationFor: { type: String, required: true },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    gender: { type: String, required: true },
    dob: { type: String },
    nationality: { type: String, required: true },
    passportNo: { type: String },
    occupation: { type: String },
    email: { type: String, required: true },
    personalEmail: { type: String },
    mobile: { type: String, required: true },
    whatsappNo: { type: String },
    indiaContactNo: { type: String },
    designation: { type: String },
    companyName: { type: String },
    companyWebsite: { type: String },
    industrySector: { type: String },
    companySize: { type: String },
    address: { type: String },
    country: { type: String },
    state: { type: String },
    city: { type: String },
    companyPincode: { type: String },
    preferredDate: { type: String },
    numAttendees: { type: String },
    invitationLetter: { type: String },
    hotelAssistance: { type: String },
    airportPickup: { type: String },
    translatorSupport: { type: String },
    conferenceInterest: { type: String },
    conferenceRole: { type: String },
    vipPass: { type: String },
    b2bMeeting: { type: String },
    whatsappUpdates: { type: String },
    specificRequirement: { type: String },
    subscribe: { type: Boolean, default: false },
    purposeOfVisit: [{ type: String }],
    areaOfInterest: [{ type: String }],
    // Document Fields
    passportCopyUrl: { type: String },
    visitingCardUrl: { type: String },
    companyProfileUrl: { type: String },
    visaDocsUrl: { type: String },
    photoIdUrl: { type: String },
    qrCode: { type: String },
    status: { type: String, default: "New Reg." },
    created_by: { type: String, default: null },
    updated_by: { type: String, default: null },
  },
  { timestamps: true },
);

module.exports = secondaryDB.model("InternationalVisitor", InternationalVisitorSchema);
