const mongoose = require("mongoose");
const { secondaryDB } = require("../config/secondaryDb");
const CrmLpu2018Schema = new mongoose.Schema(
  {
    ex_id: { type: Number, required: true },
    compny_id: { type: String, required: true },
    evnt_id: { type: String, required: true },
    ex_company: { type: String, required: true },
    ex_category: { type: String, required: true },
    ex_Nature: { type: String, required: true },
    ex_Product: { type: String, required: true },
    ex_source: { type: String, required: true },
    ex_Address: { type: String, required: true },
    ex_Country: { type: String, required: true },
    ex_State: { type: String, required: true },
    ex_city: { type: String, required: true },
    ex_pin: { type: String, required: true },
    ex_Website: { type: String, required: true },
    ex_logo: { type: String, required: true },
    ex_ctitle: { type: String, required: true },
    ex_CName: { type: String, required: true },
    ex_surname: { type: String, required: true },
    ex_Mobile: { type: String, required: true },
    ex_Landline: { type: String },
    ex_Alternate: { type: String, required: true },
    ex_Email: { type: String, required: true },
    ex_Designat: { type: String, required: true },
    ex_sName: { type: String, required: true },
    ex_sMobile: { type: String, required: true },
    ex_sLandline: { type: String, required: true },
    ex_sAlternate: { type: String, required: true },
    ex_sEmail: { type: String, required: true },
    ex_sDesignat: { type: String, required: true },
    ex_tName: { type: String, required: true },
    ex_tMobile: { type: String, required: true },
    ex_tLandline: { type: String, required: true },
    ex_tAlternate: { type: String },
    ex_tEmail: { type: String, required: true },
    ex_tDesignat: { type: String, required: true },
    ex_added_by: { type: String, required: true },
    ex_added: { type: Date, required: true },
    updated_by: {
      type: String,
      default: null,
      trim: true,
    },
  },
  { timestamps: { createdAt: "ex_added", updatedAt: "ex_updated" } },
);

module.exports = secondaryDB.model("CrmLpu2018", CrmLpu2018Schema);
